### ISSUE TITLE
3.12 Release Notes: Client Labels

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-release-notes#10]
"Client Attributes" were renamed as "Client Labels" during the development. 

We should update the "Client Instance Names and Attributes" item of the release notes. We should replace all "attributes" with "labels".

Also, the link anchor provided in the release notes should be updated accordingly.

https://docs.hazelcast.org/docs/rn/

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-release-notes/commit/047ef5aa5400246797d5e4f8efc7d260f0286788
