### ISSUE TITLE
Changes in OS Release Notes build and folder.

### ISSUE THREAD

**Issue by Serdaro** [hazelcast/hazelcast-release-notes#4]
Currently, on the Doc server, the path for OS release notes document is `../files/hazelcast-docs/release-notes` and it is built using the `bfdocs` command.

Please see the below explanations and requests.

**Path:**
- I prepared the OS release notes document in its new layout and uploaded it to a new folder on the Doc server. Path of this new folder is `../files/hazelcast-docs/rn`.
- I wrote the redirection script for the OS release notes document and put it into the current OS release notes folder on the Doc server. Now the users see the new layout up to the latest release, which is 3.8.2.
- Starting with 3.8.3, or 3.9 (whichever is suitable for you), it will be nice to change the path for the OS release notes document in the release script. The new path is `../files/hazelcast-docs/rn`.
- When this is done, I will notify Benjamin so the OS release notes links will point to this new path.

**Build:**
- So far, OS release notes document has been built by the `bfdocs .............` command executed on the repo `https://github.com/hazelcast/hazelcast-release-notes`.
- The document with the new layout requires only the command `daux` on the same repo.
- New layout's documents are reside in the "daux" branch of the repo. Once the script is updated, I will move the content of "daux" branch to "master" branch.

**Comment by hasancelik** [comment]
done --> https://github.com/hazelcast/DevOps/commit/ff720d621bbe36254f448a0c10f2e79a602378bd
