### ISSUE TITLE
Automation of EE release notes.

### ISSUE THREAD

**Issue by Serdaro** [hazelcast/hazelcast-release-notes#5]
Currently, EE release notes is built and uploaded manually. Its path has been `../files/hazelcast-docs/enterprise-release-notes` on the Doc server.

Please see the below explanations and requests.

**Repo:**
- To put the EE release notes build into the Hazelcast release cycle, a new repo is needed, i.e., "hazelcast-enterprise-release-notes". Or, we can create two folders in the "hazelcast-release-notes" repo as "OS" and "EE" (whichever option is suitable for you).

**Path:**
- I prepared the EE release notes document in its new layout and uploaded it to a new folder on the Doc server. Path of this new folder is `../files/hazelcast-docs/ern`.
- I wrote the redirection script for the EE release notes document and put it into the current EE release notes folder on the Doc server. Now the users see the new layout up to the latest release, which is 3.8.2.
- Starting with 3.8.3, or 3.9 (whichever is suitable for you), it will be nice to change the path for the EE release notes document in the release script. The new path is `../files/hazelcast-docs/ern`.
- When this is done, I will notify Benjamin so the EE release notes links will point to this new path.

**Build:**
- So far, EE release notes document has been built by the `bfdocs .............` command on my local. 
- The document with the new layout requires only the command `daux` on its repo. Please see the above **Repo:** section.

**Comment by hasancelik** [comment]
done --> https://github.com/hazelcast/DevOps/commit/f96a20388af520812e893a4193f562d20afbfb2f
